# Generated by Django 4.2.4 on 2023-09-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cartorder_cartorderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': '8. Order'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': '9. Order Items'},
        ),
    ]
