# Generated by Django 4.2.4 on 2023-09-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_cartorder_options_alter_cartorderitems_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(null=True, upload_to='cart_order_item_images/'),
        ),
    ]
