# Generated by Django 4.2.4 on 2023-10-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_useraddressbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddressbook',
            options={'verbose_name_plural': '10. User Address'},
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], default='paypal', max_length=10),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('process', 'In Process'), ('delivered', 'Delivered')], default='process', max_length=100),
        ),
    ]
