# Generated by Django 4.2.4 on 2023-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_useraddressbook_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_method_choices',
            field=models.CharField(choices=[('process', 'In Process'), ('deliverd', 'Deliverd')], default='process', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('process', 'In Process'), ('deliverd', 'Deliverd')], default='process', max_length=100),
        ),
    ]
