# Generated by Django 4.2.4 on 2023-10-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_cartorder_payment_method_choices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalIncomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('process', 'In Process'), ('deliverd', 'Deliverd'), ('Dispatched', 'Dispatched'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='process', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('cod', 'Cash on Delivery')], default='none', max_length=100),
        ),
    ]
