# Generated by Django 4.2.4 on 2023-11-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_product_quantity_productattribute_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
